### ISSUE TITLE
SVGs rendering problem in Firefox 

### ISSUE THREAD

**Issue by AniVerma17** [asetalias/hackthenight#3]
The HTN logo and tagline, both created in SVG, are not rendering in Firefox.
![capture](https://user-images.githubusercontent.com/24977899/35855504-71cc79c2-0b59-11e8-9707-5fd7b4e0d2af.PNG)
Chrome and Edge are rendering them without any glitch.

@thisisayush immediate fix is required.

**Comment by thisisayush** [comment]
Wil take a look at it.
